x-base-env: &x-base-env
  RELEASE: 2023+compose
  RUBY_BACKEND: http://localhost:4567
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: bad-password
  DB_DATABASE: postgres

services:
  react:
    build: react
    ports: [3000:3000]
  flask:
    build: flask
    environment:
      <<: *x-base-env
      FLASK_ENV: test
      FLASK_APP_DSN: http://flask@localhost:9001/2
    ports: [8080:8080]
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=bad-password
